public class _18_exception {
    public static void main(String[] args){
        int i = 1;
        int j = 0;
        
        int[] arr = new int[4];
        i = i/j;
        // try{
        //     // for (int k = 1; k < 5; k++) {
        //     //     arr[k] = k+1;
        //     // }
        // }
        // catch(ArithmeticException ae){
        //     System.out.println(ae);
        // }
        // catch(Exception e){
        //     System.out.println(e);
        // }

        // System.out.println("Hello");
    }
}
